# The config of the 15x15x23a scenario
name: Connector-v2
task_name: con-5x5x3a

task_config:
  grid_size: 5
  num_agents: 3

env_kwargs:
  time_limit: 25

# n_agents: 3, 5, 7, 10, 13, 15, 17, 21, 23
# grid size: 5, 7, 8, 10, 11, 12, 13, 14, 15