defaults:
  - _self_

scenario_config_path: mava/configs/env/scenario

scenario:
  name: "placeholder"
  task_config: {}
  # max_grid_dimension: 10 
  # max_n_agents: 10 

default_task_kwargs:
    {}

tasks:
  # - name: tiny-4ag
  #   scenario_key: env.scenario.name
  #   scenario_value: RobotWarehouse-v0
  #   scenario_file_name: tiny-4ag
  #   eval_metric: "episode_return" 
  #   implicit_agent_id: False 
  #   log_win_rate: False 
  #   task_kwargs: 
  #     time_limit: 500  

  # - name: small-4ag
  #   scenario_key: env.scenario.name
  #   scenario_value: RobotWarehouse-v0
  #   scenario_file_name: small-4ag
  #   eval_metric: "episode_return"
  #   implicit_agent_id: False
  #   log_win_rate: False
  #   task_kwargs: 
  #     time_limit: 500 

  # - name: medium-4ag
  #   scenario_key: env.scenario.name
  #   scenario_value: RobotWarehouse-v0
  #   scenario_file_name: medium-4ag
  #   eval_metric: "episode_return"
  #   implicit_agent_id: False
  #   log_win_rate: False
  #   task_kwargs: 
  #     time_limit: 500 

  # - name: large-4ag
  #   scenario_key: env.scenario.name
  #   scenario_value: RobotWarehouse-v0
  #   scenario_file_name: large-4ag
  #   eval_metric: "episode_return"
  #   implicit_agent_id: False
  #   log_win_rate: False
  #   task_kwargs: 
  #     time_limit: 500 

  - name: xlarge-4ag
    scenario_key: env.scenario.name
    scenario_value: RobotWarehouse-v0
    scenario_file_name: xlarge-4ag 
    eval_metric: "episode_return"
    implicit_agent_id: False
    log_win_rate: False
    task_kwargs: 
      time_limit: 500 

envs_name:
  - name: RobotWarehouse
  # - name: RobotWarehouse
  # - name: RobotWarehouse
  # - name: RobotWarehouse
  # - name: RobotWarehouse