defaults:
  - _self_
  
scenario_config_path: mava/configs/env/scenario 

scenario: 
  name: "placeholder" 
  task_config: {} 

tasks:
  - name: tiny-4ag
    scenario_key: env.scenario.name 
    scenario_value: RobotWarehouse-v0
    scenario_file_name: tiny-4ag 

  - name: small-4ag
    scenario_key: env.scenario.name 
    scenario_value: RobotWarehouse-v0
    scenario_file_name: small-4ag 

  - name: medium-4ag
    scenario_key: env.scenario.name 
    scenario_value: RobotWarehouse-v0
    scenario_file_name: medium-4ag 


  - name: large-4ag
    scenario_key: env.scenario.name 
    scenario_value: RobotWarehouse-v0
    scenario_file_name: large-4ag 


  - name: xlarge-4ag
    scenario_key: env.scenario.name 
    scenario_value: RobotWarehouse-v0
    scenario_file_name: small-4ag 



envs_name:  
  - name: RobotWarehouse  
  - name: RobotWarehouse
  - name: RobotWarehouse  
  - name: RobotWarehouse  
  - name: RobotWarehouse


eval_metric: episode_return
implicit_agent_id: False
log_win_rate: False
kwargs:
  time_limit: 500


# tiny-4ag
# small-4ag
# medium-4ag
# large-4ag
# xlarge-4ag