
env_name: RobotWarehouse  # Used for logging purposes.
eval_metric: episode_return
implicit_agent_id: false
log_win_rate: false
kwargs:
  time_limit: 500
scenario:
  name: RobotWarehouse-v0
  task_names: [tiny-2ag, small-4ag]  # List of scenarios to run.
  task_config:
    column_height: 8
    shelf_rows: 2
    shelf_columns: 3
    num_agents: 4
    sensor_range: 1
    request_queue_size: 4
  env_kwargs: {}
