defaults:
  - _self_
  
scenario_config_path: mava/configs/env/scenario 

scenario: 
  name: "placeholder" 
  task_config: {} 

tasks:
  - name: tiny-4ag
    scenario_key: env.scenario.name 
    scenario_value: RobotWarehouse-v0
    scenario_file_name: tiny-4ag 

  - name: tiny-4ag-hard
    scenario_key: env.scenario.name 
    scenario_value: RobotWarehouse-v0
    scenario_file_name: tiny-4ag-hard 

env_name: RobotWarehouse  
eval_metric: episode_return
implicit_agent_id: False
log_win_rate: False
kwargs:
  time_limit: 500
